apiVersion: v1
kind: Service
metadata:
  name: weather-app-service
spec:
  selector:
    app: weather-app # This matches the label on your Deployment's pods
  ports:
    - protocol: TCP
      port: 80 # The port the service exposes
      targetPort: 5000 # The port your container is listening on
      nodePort: 30000 # Optional: A specific port on the node (e.g., for Minikube). Must be 30000-32767.
  type: NodePort # Or LoadBalancer if deploying to a cloud provider like GKE/EKS/AKS
